### ISSUE TITLE
unit test fails

### ISSUE THREAD

**Issue by petacube** [StatisKit/AutoWIG#53]
using python 3.5 on MacBook
py.test
============================= test session starts ==============================
platform darwin -- Python 3.5.3, pytest-3.1.2, py-1.4.34, pluggy-0.4.0
rootdir: /workAutoWIG, inifile:
plugins: xdist-1.14, cov-2.2.1
collected 0 items / 3 errors 

==================================== ERRORS ====================================
_____________________ ERROR collecting test/test_basic.py ______________________
../../../../anaconda3/lib/python3.5/site-packages/_pytest/python.py:408: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
../../../../anaconda3/lib/python3.5/site-packages/py/_path/local.py:662: in pyimport
    __import__(modname)
E     File "/workAutoWIG/test/test_basic.py", line 42
E       exec code in globals()
E               ^
E   SyntaxError: invalid syntax
____________________ ERROR collecting test/test_feedback.py ____________________
ImportError while importing test module '/workAutoWIG/test/test_feedback.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test_feedback.py:17: in <module>
    import autowig
../../../../anaconda3/lib/python3.5/site-packages/autowig-1.0.0-py3.5.egg/autowig/__init__.py:35: in <module>
    from ._feedback import feedback
../../../../anaconda3/lib/python3.5/site-packages/autowig-1.0.0-py3.5.egg/autowig/_feedback.py:18: in <module>
    import parse
E   ImportError: No module named 'parse'
_____________________ ERROR collecting test/test_subset.py _____________________
../../../../anaconda3/lib/python3.5/site-packages/_pytest/python.py:408: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
../../../../anaconda3/lib/python3.5/site-packages/py/_path/local.py:662: in pyimport
    __import__(modname)
E     File "/workAutoWIG/test/test_subset.py", line 44
E       exec code in globals()
<E               ^

**Comment by pfernique** [comment]
This is because Python 3 is not yet supported. See issue #54.
