### ISSUE TITLE
base class method

### ISSUE THREAD

**Issue by akirayu101** [StatisKit/AutoWIG#58]
how can i export base class method?

**Comment by pfernique** [comment]
Can you be more specific ?
Have you a small example of what you want to do ?

**Comment by akirayu101** [comment]
I am using crtp for singleton base class

template \<typename T>
class Singleton {
public:
  static T& Instance();
}

then in my impletation class 

class FooSingleton final : public Singleton\<FooSingleton> {
}

I want FooSingleton autogen binding consist the "Instance" static method too

**Comment by pfernique** [comment]
Normally, the `Singleton<FooSingleton>` is exported with a complex name in python (e.g., `_Singleton_0caufauo613weugfw`)  and the `instance()` method is present in this class.

**Comment by pfernique** [comment]
Any news ?

**Comment by pfernique** [comment]
Closing issue since there is no news
