### ISSUE TITLE
Make a try at CastXML

### ISSUE THREAD

**Issue by pradal** [StatisKit/AutoWIG#8]
Hi @pfernique, 
XDress has lots of problems with libclang.

KitWare recently release CastXML, a replacement of gcc-xml, ported to c++-11.
It will be usefull to try it.

**Comment by pfernique** [comment]
Since we resolved problems with libclang using StatisKit/PyClangLite this adding a new parser for C++ libraries is not our priority.
In the next stage we will focus on:
- SCons integration,
- Rcpp wrapping.
